name: Android Release Build

on:
  push:
    tags:
      - 'v*' # Chạy khi có tag mới như v1.0.0
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Quan trọng để lấy được lịch sử git cho versionCode

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Bước giải mã Keystore từ Secret
      - name: Decode Keystore
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 --decode > app/release-keystore.jks

      - name: Build Release APK
        run: ./gradlew assembleProdRelease
        env:
          RELEASE_KEYSTORE_PATH: "release-keystore.jks"
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TreeTask-Release-APK
          path: app/TreeTask_*.apk
